### ISSUE TITLE
Make it easy to copy timur.mobi/user weblink

### ISSUE THREAD

**Issue by xandro0777** [mehrvarz/webcall-android#6]
.. so it can be easily shared by any method available like email or text messaging.

**Comment by mehrvarz** [comment]
This should work already.

I would like to make this work with any domain configured by the user, but unfortunately [Android intent filters](https://github.com/mehrvarz/webcall-android/blob/59150d7b0cb9a148b62dc10cdfaedc9cbca8189e/src/main/AndroidManifest.xml#L52) are static. This is why it will currently only work with the server on timur.mobi.

If you have WebCall app installed and you click on a timur.mobi/user/... link, you should be offered to open this link in WebCall (instead of a browser) and make a call directly. Please give it a try.

**Comment by xandro0777** [comment]
No.. I am looking at the reverse scenario:  I have installed the webcall app,  created an id and want to send that id/url easily to my friends by email or text.  I haven't found a way how to copy the url to clipboard or export it from the app.

**Comment by mehrvarz** [comment]
Misunderstood. Clicking on "You will receive calls made by this link" copies your user link to the clipboard.

**Comment by xandro0777** [comment]
Works nicely. The reason I could not figure it out was that I was used to long-tap which opens the Android options instead. Maybe a share icon would help people like me to figure out the obvious.

**Comment by mehrvarz** [comment]
Core WebCall is a web app and there is no long-tap for web apps. (OTOH, web browsers have the best WebRTC implementations.) Anyways, I will think of something and improve this functionality.

**Comment by mehrvarz** [comment]
[WebCall-1.0.0-rc4.apk](https://timur.mobi/webcall/_dl/WebCall-1.0.0-rc4.apk) supports long-press on links (like the /user/ link discussed here) for clipboard copy.
