### ISSUE TITLE
please add an option so when user turn it on, the app only make connections through tcp?

### ISSUE THREAD

**Issue by rustforfuture** [mehrvarz/webcall-android#8]
Hello

I live in a "internet hostile" reign that manipulate traffics very much and blocks udp or make it unusable to use it for calls and such (tcp also but....)

May you please add an option so when user turn it on, the app only make connections through tcp?

It will be great.

So maybe we can tun the server on local network also in case of internet shutdowns and can call in heavily restricted network with our friends, family and co-workers.

Thank you

**Comment by mehrvarz** [comment]
> app only make connections through tcp

RTC over TCP through NAT is not technically possible.

If you mean TCP over TURN: Routine (frequent) use of TURN is discouraged due to traffic cost on the server side. Also, using TURN results in degraded quality and higher latency, even if proxying UDP.

> I live in a "internet hostile" reign that manipulate traffics very much

Where is this taking place? Does regular WebRTC (over UDP) work sometimes, or never?

**Comment by mehrvarz** [comment]
> Countries like Kazakhstan, china, Syria, Lebanon, Afghanistan, india, Iran and many more that they called enemies of the internet.

When I call people in (some of) these countries, it usually works fine. Too bad I cannot look at your env. Did you consider fetching your adb logcat? (Android device must be connected via USB and ADB debugging must be enabled:)
> adb devices
> adb -s deviceID logcat |grep -E "WebCall|webcall|Runtime|System.err"

Switching to TCP-over-TURN can certainly not solve "sabotage"-like issues.
